version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app-api
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstallHook.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/AfterInstallHook.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root